In [ ]:
import numpy as np 
import pandas as pd 

In [ ]:
import os
for dirname, _, filenames in os.walk('/kaggle/input/nlp-specialization-data/'):
    print(dirname)

In [ ]:
def read_file(filepath):
    
    with open(filepath) as f:
        str_text = f.read()
    
    return str_text

In [ ]:
len("rahul")

5

In [ ]:
len(read_file('/content/Novel - Moby-Dick By Herman Melville.txt'))

1198622

In [ ]:
print(read_file('/content/Novel - Moby-Dick By Herman Melville.txt')[:5000])

CHAPTER 1

Loomings.


Call me Ishmael.  Some years ago--never mind how long
precisely--having little or no money in my purse, and nothing
particular to interest me on shore, I thought I would sail about a
little and see the watery part of the world.  It is a way I have of
driving off the spleen and regulating the circulation.  Whenever I
find myself growing grim about the mouth; whenever it is a damp,
drizzly November in my soul; whenever I find myself involuntarily
pausing before coffin warehouses, and bringing up the rear of every
funeral I meet; and especially whenever my hypos get such an upper
hand of me, that it requires a strong moral principle to prevent me
from deliberately stepping into the street, and methodically knocking
people's hats off--then, I account it high time to get to sea as soon
as I can.  This is my substitute for pistol and ball.  With a
philosophical flourish Cato throws himself upon his sword; I quietly
take to the ship.  There is nothing surprising in this

In [ ]:
import spacy
import en_core_web_sm

nlp = en_core_web_sm.load()
nlp.max_length = 1198623

In [ ]:
def read_file(filepath):
    
    with open(filepath) as f:
        str_text = f.read()
    
    return str_text[:250000]

In [ ]:
def separate_punc(doc_text):
    return [token.text.lower() for token in nlp(doc_text) if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n ']

In [ ]:
d = read_file('/content/Novel - Moby-Dick By Herman Melville.txt')
tokens = separate_punc(d)

In [ ]:
type(tokens)

list

In [ ]:
len(tokens)

45279

In [ ]:
tokens[:10]

['chapter',
 '1',
 'loomings',
 'call',
 'me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never']

In [ ]:
# organize into sequences of tokens
train_len = 25+1 # 25 training words , then one target word

# Empty list of sequences
text_sequences = []

for i in range(train_len, len(tokens)):
    
    # Grab train_len# amount of characters
    seq = tokens[i-train_len:i]
    
    # Add to list of sequences
    text_sequences.append(seq)

In [ ]:
print(read_file('/content/Novel - Moby-Dick By Herman Melville.txt')[:1000])

CHAPTER 1

Loomings.


Call me Ishmael.  Some years ago--never mind how long
precisely--having little or no money in my purse, and nothing
particular to interest me on shore, I thought I would sail about a
little and see the watery part of the world.  It is a way I have of
driving off the spleen and regulating the circulation.  Whenever I
find myself growing grim about the mouth; whenever it is a damp,
drizzly November in my soul; whenever I find myself involuntarily
pausing before coffin warehouses, and bringing up the rear of every
funeral I meet; and especially whenever my hypos get such an upper
hand of me, that it requires a strong moral principle to prevent me
from deliberately stepping into the street, and methodically knocking
people's hats off--then, I account it high time to get to sea as soon
as I can.  This is my substitute for pistol and ball.  With a
philosophical flourish Cato throws himself upon his sword; I quietly
take to the ship.  There is nothing surprising in this

In [ ]:
' '.join(text_sequences[0])

'chapter 1 loomings call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to'

In [ ]:
' '.join(text_sequences[1])

'1 loomings call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest'

In [ ]:
' '.join(text_sequences[2])

'loomings call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me'

In [ ]:
len(text_sequences)

45253

In [ ]:
len(tokens)

45279

In [ ]:
print(len(text_sequences[0]))
print(text_sequences[0])

26
['chapter', '1', 'loomings', 'call', 'me', 'ishmael', 'some', 'years', 'ago', 'never', 'mind', 'how', 'long', 'precisely', 'having', 'little', 'or', 'no', 'money', 'in', 'my', 'purse', 'and', 'nothing', 'particular', 'to']


In [ ]:
from keras.preprocessing.text import Tokenizer

In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_sequences)
sequences = tokenizer.texts_to_sequences(text_sequences)

In [ ]:
print(len(sequences[0]))
print(sequences[0])

26
[187, 7000, 6999, 516, 24, 432, 65, 232, 640, 100, 223, 99, 93, 1331, 277, 68, 48, 36, 639, 6, 31, 1028, 2, 150, 431, 5]


In [ ]:
type(tokenizer.index_word)

dict

In [ ]:
' '.join(text_sequences[0])

'chapter 1 loomings call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to'

In [ ]:
i=0
for a in tokenizer.index_word:
    print(a,"--->",tokenizer.index_word[a])
    i+=1
    if i==20 : break 

1 ---> the
2 ---> and
3 ---> of
4 ---> a
5 ---> to
6 ---> in
7 ---> i
8 ---> that
9 ---> his
10 ---> he
11 ---> it
12 ---> was
13 ---> but
14 ---> with
15 ---> all
16 ---> for
17 ---> as
18 ---> 's
19 ---> at
20 ---> is


In [ ]:
for i in sequences[0]:
    print(f'{i} : {tokenizer.index_word[i]}')

187 : chapter
7000 : 1
6999 : loomings
516 : call
24 : me
432 : ishmael
65 : some
232 : years
640 : ago
100 : never
223 : mind
99 : how
93 : long
1331 : precisely
277 : having
68 : little
48 : or
36 : no
639 : money
6 : in
31 : my
1028 : purse
2 : and
150 : nothing
431 : particular
5 : to


In [ ]:
i=0
for a in tokenizer.word_counts:
    print((a,tokenizer.word_counts[a]))
    i+=1
    if i==10 : break 

('chapter', 807)
('1', 2)
('loomings', 3)
('call', 238)
('me', 6214)
('ishmael', 292)
('some', 2451)
('years', 606)
('ago', 191)
('never', 1700)


In [ ]:
vocabulary_size = len(tokenizer.word_counts)
vocabulary_size

7000

In [ ]:
i=6990
for a in range(i,7000):
    print(a,"--->",tokenizer.index_word[a])
    #i+=1
    #if i==6999 : break 

6990 ---> subtle
6991 ---> conceived
6992 ---> poorly
6993 ---> moods
6994 ---> whimsicalities
6995 ---> apprehensiveness
6996 ---> uneasiness
6997 ---> warrantry
6998 ---> emotions
6999 ---> loomings


In [ ]:
import numpy as np

In [ ]:
len(sequences)

45253

In [ ]:
len(sequences[0])

26

In [ ]:
sequences = np.array(sequences)

In [ ]:
sequences.shape

(45253, 26)

In [ ]:
sequences

array([[ 187, 7000, 6999, ...,  150,  431,    5],
       [7000, 6999,  516, ...,  431,    5,  734],
       [6999,  516,   24, ...,    5,  734,   24],
       ...,
       [  86,  578,    7, ...,  472,   14,    1],
       [ 578,    7,  171, ...,   14,    1,  111],
       [   7,  171,    5, ...,    1,  111,  577]])

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense,LSTM,Embedding

In [ ]:
def create_model(vocabulary_size, seq_len):
    model = Sequential()
    model.add(Embedding(vocabulary_size, 25, input_length=seq_len))
    model.add(LSTM(150, return_sequences=True))
    model.add(LSTM(150))
    model.add(Dense(150, activation='relu'))

    model.add(Dense(vocabulary_size, activation='softmax'))
    
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
   
    model.summary()
    
    return model

In [ ]:
from tensorflow.keras.utils import to_categorical

In [ ]:
print(sequences.shape)
sequences

(45253, 26)


array([[ 187, 7000, 6999, ...,  150,  431,    5],
       [7000, 6999,  516, ...,  431,    5,  734],
       [6999,  516,   24, ...,    5,  734,   24],
       ...,
       [  86,  578,    7, ...,  472,   14,    1],
       [ 578,    7,  171, ...,   14,    1,  111],
       [   7,  171,    5, ...,    1,  111,  577]])

In [ ]:
print(sequences[:,:-1].shape)
sequences[:,:-1]

(45253, 25)


array([[ 187, 7000, 6999, ...,    2,  150,  431],
       [7000, 6999,  516, ...,  150,  431,    5],
       [6999,  516,   24, ...,  431,    5,  734],
       ...,
       [  86,  578,    7, ...,    1,  472,   14],
       [ 578,    7,  171, ...,  472,   14,    1],
       [   7,  171,    5, ...,   14,    1,  111]])

In [ ]:
# last Word
print(sequences[:,-1].shape)
sequences[:,-1]

(45253,)


array([  5, 734,  24, ...,   1, 111, 577])

In [ ]:
X = sequences[:,:-1]

In [ ]:
X.shape

(45253, 25)

In [ ]:
y = sequences[:,-1]

In [ ]:
y.shape

(45253,)